top: http://<%= ENV['WEB_DOMAIN'] %>/
reviewers:
  pulls:
    show: http://<%= ENV['WEB_DOMAIN'] %>/reviewers/pulls/
reviewees:
  memberships:
    join: http://<%= ENV['WEB_DOMAIN'] %>/reviewees/memberships/join?
